### ISSUE TITLE
java客户端应该怎么连接上?

### ISSUE THREAD

**Issue by aohanhongzhi** [xuanyanwow/LogkitByGo#1]
尝试java的socket对接通信，然后以失败告终。

**Comment by xuanyanwow** [comment]
请问方便联系我qq吗？59419979



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: aohanhongzhi <notifications@github.com&gt;
发送时间: 2020年3月19日 22:08
收件人: xuanyanwow/LogkitByGo <LogkitByGo@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[xuanyanwow/LogkitByGo] java客户端应该怎么连接上? (#1)





 
尝试java的socket对接通信，然后以失败告终。

**Comment by xuanyanwow** [comment]
java上报教程https://github.com/xuanyanwow/LogkitByGo/blob/master/document/reportCode/java.md

**Comment by xuanyanwow** [comment]
java上报教程https://github.com/xuanyanwow/LogkitByGo/blob/master/document/reportCode/java.md
